out_vcodec: hevc_nvenc # hevc_nvenc | h264_nvenc | libx264 | libx265
out_pix_fmt: yuv420p
output_args:
    crf: 0
    # preset: ultrafast # movflags faststart
in_global_args: '-hide_banner -loglevel error'
out_global_args: '-hide_banner -loglevel error'
max_timeout: 15