out_vcodec: hevc_nvenc # hevc_nvenc | h264_nvenc | libx264 | libx265
out_pix_fmt: yuv444p16le  # yuv444p16le yuvj420p
output_args:
    preset: p7
    tune: lossless
in_global_args: '-hide_banner -loglevel warning -nostdin'
out_global_args: '-hide_banner -loglevel warning'
max_timeout: 15