model_type: torch
image_format: rgb
use_fp16: True
classes: mapillary
config_file: configs/mapillary-vistas/semantic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_300k.yaml
opts: []
weights_path: weights/model_final_90ee2d.pkl
input_shape: [2048, 1024] # width, height - bs 3
# input_shape: [1024, 512] # width, height - bs 8
# input_shape: [1280, 512] # width, height - bs 8
img_mean: null # Already fused in the model
img_std: null # Already fused in the model
batch_size: 3
num_workers: 4