model_type: torch
image_format: rgb
use_fp16: True
classes: cityscapes
config_file: configs/cityscapes/semantic-segmentation/maskformer2_R50_bs16_90k.yaml
opts: []
weights_path: weights/sem-r50-cityscapes.pkl
input_shape: [2048, 1024] # width, height - bs 6
# input_shape: [1024, 512] # width, height - bs 15
img_mean: null # Already fused in the model
img_std: null # Already fused in the model
batch_size: 6
num_workers: 4