model_type: torch
image_format: rgb
use_fp16: True
classes: cityscapes
config_file: configs/cityscapes/semantic-segmentation/swin/maskformer2_swin_base_IN21k_384_bs16_90k.yaml
opts: []
weights_path: weights/sem-swin-m-cityscapes.pkl
input_shape: [2048, 1024] # width, height
img_mean: null # Already fused in the model
img_std: null # Already fused in the model
batch_size: 4
num_workers: 4