model_type: onnx
image_format: rgb
classes: cityscapes
weights_path: 'weights/bisenetv2-fp16.onnx'
providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'] # 'TensorrtExecutionProvider'
img_mean: [123.675, 116.28, 103.53]
img_std: [58.395, 57.12, 57.375]
num_workers: 4
input_shapes:
  2048,1024: 3
  1024,512: 12
  768,384: 12
  512,512: 12