model_type: onnx
image_format: rgb
classes: cityscapes
weights_path: 'weights/bisectv1-dynamic.onnx'
providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'] # 'TensorrtExecutionProvider'
input_shape: [2048, 1024] # width, height - bs 3
# input_shape: [1024, 512] # width, height - bs 12
img_mean: [123.675, 116.28, 103.53]
img_std: [58.395, 57.12, 57.375]
batch_size: 3
num_workers: 4